# Generated by Django 5.1.5 on 2025-01-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='media/service_images/'),
        ),
    ]
