# Generated by Django 5.1.5 on 2025-01-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosite', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=100)),
                ('role', models.CharField(choices=[('counselor', 'Counselor'), ('manager', 'Manager'), ('support', 'Support Staff'), ('admin', 'Administrator')], help_text='Role in the team', max_length=50)),
                ('email', models.EmailField(help_text='Email address', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=15)),
                ('expertise', models.TextField(blank=True, help_text='Areas of expertise or specialization')),
                ('qualification', models.CharField(blank=True, help_text='Qualifications of the team member', max_length=255)),
                ('short_description', models.TextField(blank=True, help_text='A brief description of the team member')),
                ('date_joined', models.DateField(auto_now_add=True, help_text='Date the team member joined')),
                ('is_active', models.BooleanField(default=True, help_text='Is the team member currently active?')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['name'],
            },
        ),
    ]
